// src/constants/screens.ts
const SCREENS = {
    SUBMISSION_COMPLETE: "SUBMISSION_COMPLETE",
    SPLASH: "SPLASH",
    AUTH: "AUTH",
    PROFILE_SETUP: "PROFILE_SETUP",
    HOME: "HOME",
    ACTIVE_CAMPAIGNS: "ACTIVE_CAMPAIGNS",
    MY_CAMPAIGNS: "MY_CAMPAIGNS",
    CAMPAIGNS: "CAMPAIGNS",
    PROFILE: "PROFILE",
    CAMPAIGN_DETAILS: "CAMPAIGN_DETAILS",
    VIDEO_SUBMISSION: "VIDEO_SUBMISSION",
    WALLET: "WALLET",
    WITHDRAW: "WITHDRAW",
    WITHDRAWAL_SUCCESS: "WITHDRAWAL_SUCCESS",
    NOTIFICATIONS: "NOTIFICATIONS",
    PRIVACY_POLICY: "PRIVACY_POLICY",
    TERMS_AND_CONDITIONS: "TERMS_AND_CONDITIONS",
  };
  
  export default SCREENS;